export type START_DEVICE_AUTHENTICATION_TYPE = 'START_DEVICE_AUTHENTICATION';
export const START_DEVICE_AUTHENTICATION: START_DEVICE_AUTHENTICATION_TYPE =
  'START_DEVICE_AUTHENTICATION';
export function startDeviceAuthentication() {
  return { type: START_DEVICE_AUTHENTICATION };
}
export type DEVICE_SETUP_ACTION_TYPE = 'DEVICE_SETUP_ACTION';
export const DEVICE_SETUP_ACTION: DEVICE_SETUP_ACTION_TYPE =
  'DEVICE_SETUP_ACTION';
export function setupDevice() {
  return { type: DEVICE_SETUP_ACTION };
}
