import {
  ERROR_FETCH_ACTION_TYPE,
  START_FETCH_ACTION_TYPE,
  SUCCESS_FETCH_ACTION_TYPE
} from '@chilco/middlewares';
import {
  SOCKET_SET_TOKEN_ACTION_TYPE,
  SOCKET_REFRESH_TOKEN_ACTION_TYPE,
  SOCKET_VALIDATE_TOKEN_ACTION_TYPE
} from './socket';
import { FetchActionType } from './api';
import {
  DEVICE_SETUP_ACTION_TYPE,
  START_DEVICE_AUTHENTICATION_TYPE
} from './device';
import { CLOSE_MODAL_TYPE, SHOW_MODAL_TYPE } from './model';
import { CLOSE_ALERT_TYPE, SHOW_ALERT_TYPE } from './alert';

export type ActionType =
  | FetchActionType
  | ERROR_FETCH_ACTION_TYPE
  | START_FETCH_ACTION_TYPE
  | SUCCESS_FETCH_ACTION_TYPE
  | SOCKET_SET_TOKEN_ACTION_TYPE
  | SOCKET_REFRESH_TOKEN_ACTION_TYPE
  | SOCKET_VALIDATE_TOKEN_ACTION_TYPE
  | START_DEVICE_AUTHENTICATION_TYPE
  | DEVICE_SETUP_ACTION_TYPE
  | SHOW_MODAL_TYPE
  | CLOSE_MODAL_TYPE
  | SHOW_ALERT_TYPE
  | CLOSE_ALERT_TYPE;
export interface Action {
  payload?: any;
  type?: ActionType;
}
