export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const GET_REGISTER_TOKEN = 'GET_REGISTER_TOKEN';
export const SET_REGISTER_TOKEN = 'SET_REGISTER_TOKEN';
