export const SET_TOKEN: 'SET_TOKEN' = 'SET_TOKEN';
export const REFRESH_TOKEN: 'REFRESH_TOKEN' = 'REFRESH_TOKEN';
export const VALIDATE_TOKEN: 'VALIDATE_TOKEN' = 'VALIDATE_TOKEN';

export type SocketActionType = 'SET_TOKEN' | 'VALIDATE_TOKEN' | 'REFRESH_TOKEN';
